---
title: "HAT SQL in R"
author: "Petra Hermankova"
date: "2023-08-24"
output: html_document
---
```{r}
library(RPostgreSQL)
```


```{r}
dsn_database = "<HAT>"   # Specify the name of your Database
# Specify host name e.g.:"aws-us-east-1-portal.4.dblayer.com"
dsn_hostname = "<localhost>"  
dsn_port = "<98939>"                # Specify your port number. e.g. 98939
dsn_uid = "<admin>"         # Specify your username. e.g. "admin"
dsn_pwd = "<admin>"        # Specify your password. e.g. "xxx"
```

```{r}
tryCatch({
    drv <- dbDriver("PostgreSQL")
    print("Connecting to Database…")
    connec <- dbConnect(drv, 
                 dbname = dsn_database,
                 host = dsn_hostname, 
                 port = dsn_port,
                 user = dsn_uid, 
                 password = dsn_pwd)
    print("Database Connected!")
    },
    error=function(cond) {
            print("Unable to connect to Database.")
    })
```

```{r}
dbSendQuery(connec, "DROP TABLE IF EXISTS Employees")
dbSendQuery(connec, "CREATE TABLE Employees(Id INTEGER PRIMARY KEY, Name VARCHAR(20))")
dbSendQuery(connec, "INSERT INTO Employees VALUES(1,'Aakash')")
dbSendQuery(connec, "INSERT INTO Employees VALUES(2,'Diksha')")
dbSendQuery(connec, "INSERT INTO Employees VALUES(3,'Jaskaran')")
dbSendQuery(connec, "INSERT INTO Employees VALUES(4,'Arsalan')")
dbSendQuery(connec, "INSERT INTO Employees VALUES(5,'Argha')")
dbSendQuery(connec, "INSERT INTO Employees VALUES(6,'Anuj')")
dbSendQuery(connec, "INSERT INTO Employees VALUES(7,'Noor')")
dbSendQuery(connec, "INSERT INTO Employees VALUES(8,'Anirudh')")
```

